
	$(document).ready(function(){
		"use strict";


	/* progressively enhance responsive navigation with animations */
		$('#header').Nav({
			contactToggler          : $('#isQuickContactOpen'),
			subnavToggler           : $('#topNavInput'),
			contactContainer        : $('#quick-contact'),
			subnav                  : $('.topNav-links:first'),
			serviceToggler          : $('#services-toggler'),
			serviceFadeables        : $('.fadeable'),
			serviceTogglerMinWidth  : 960
		});


		ContactForm7_Override._init($('#quick-contact'));




	/* manage second slider
	 * ------------------------------------ */
		var mainSlider_el = $("#project-slider-main");

		mainSlider_el.royalSlider({
			autoScaleSlider      : true,
			autoScaleSliderWidth : 728,
			autoScaleSliderHeight: 455,
			controlsInside       : true,
			imageScaleMode       : 'fill',
			imageScalePadding    : 0,
			slidesSpacing        : 0,
			fullscreen           : {  enabled: true,
																native : true
															}
		});

		/* these puppies have to be set after the slider was initiated, as they are generated by it */
		var mainSlider          = mainSlider_el.data('royalSlider'),
				mainSlider_bullets  = $('.rsBullets', mainSlider_el).wrap('<div class="rsBullets-container" />').parent();

		/* append left arrow */
		$('<a class="rsArrow rsArrowLeft"><span class="rsArrowIcn">&lt;</span></a>').prependTo(mainSlider_bullets).on('click', function(){
			mainSlider.prev();
		});

		/* append right arrow */
		$('<a class="rsArrow rsArrowRight"><span class="rsArrowIcn">&gt;</span></a>').appendTo(mainSlider_bullets).on('click', function(){
			mainSlider.next();
		});




	/* manage second slider
	 * ------------------------------------ */
		var secondarySlider_el = $('#project-secondarySlider');

		secondarySlider_el.royalSlider({
			autoScaleSlider      : true,
			autoScaleSliderWidth : 960,
			autoScaleSliderHeight: 690,
			controlsInside       : true,
			imageScaleMode       : 'fill',
			globalCaption        : true,
			imageScalePadding    : 0,
			slidesSpacing        : 0,
			fullscreen           : {  enabled: true,
																native : true
															}
		});

		/* these puppies have to be set after the slider was initiated, as they are generated by it */
		var secondarySlider         = secondarySlider_el.data('royalSlider'),
				secondarySlider_bullets = $('.rsBullets', secondarySlider_el).wrap('<div class="rsBullets-container" />').parent();

		/* append left arrow */
		$('<a class="rsArrow rsArrowLeft"><span class="rsArrowIcn">&lt;</span></a>').prependTo(secondarySlider_bullets).on('click', function(){
			secondarySlider.prev();
		});

		/* append right arrow */
		$('<a class="rsArrow rsArrowRight"><span class="rsArrowIcn">&gt;</span></a>').appendTo(secondarySlider_bullets).on('click', function(){
			secondarySlider.next();
		});

		/* append data attributes to each bullet so they can be shown as pseudoelement tooltips on hover */
		for( var s in secondarySlider.slides ){
			if( secondarySlider.slides.hasOwnProperty(s) ){
				secondarySlider_bullets.find('.rsBullet span').addClass('rsBullet-tooltip').eq(s).attr('data-label', secondarySlider.slides[s].caption.text());
			}
		}








		var tertiarySlider_el = $('#project-tertiarySlider');
		tertiarySlider_el.royalSlider({
			autoScaleSlider         : true,
			autoScaleSliderWidth    : 640,
			autoScaleSliderHeight   : 640,
			controlNavigationSpacing: 0,
			controlsInside          : true,
			imageScaleMode          : 'fill',
			arrowsNav               : false,
			globalCaption           : true,
			imageScalePadding       : 0,
			slidesSpacing           : 0
		});

		/* these puppies have to be set after the slider was initiated, as they are generated by it */
		var tertiarySlider          = tertiarySlider_el.data('tertiarySlider'),
				tertiarySlider_bullets  = $('.rsBullets', tertiarySlider_el).wrap('<div class="rsBullets-container" />').parent();

		/* append left arrow */
		$('<a class="rsArrow rsArrowLeft"><span class="rsArrowIcn">&lt;</span></a>').prependTo(tertiarySlider_bullets).on('click', function(){
			tertiarySlider.prev();
		});

		/* append right arrow */
		$('<a class="rsArrow rsArrowRight"><span class="rsArrowIcn">&gt;</span></a>').appendTo(tertiarySlider_bullets).on('click', function(){
			tertiarySlider.next();
		});

		tertiarySlider_bullets.find('.rsBullet span').attr('data-label', '6666');

	});

	$(window).load(function(){


		/* Load latest tweet */
		Twitter._loadFeed({

			target		: $('#twitterBalloon'),
			username	: 'aardvarkmedia',
			tweetNum	: 1,
			attrs			: {rel:'nofollow'}

		});


	});